# Generated by Django 4.0.1 on 2023-01-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myrecordentry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(db_column='Username', max_length=25)),
                ('password', models.CharField(max_length=35)),
                ('dob', models.DateField(db_column='DOB')),
            ],
            options={
                'db_table': 'myrecordentry',
                'managed': True,
            },
        ),
    ]
